# Generated by Django 3.0.6 on 2020-11-10 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name_page', models.CharField(max_length=128, verbose_name='Nombre de la Pagina')),
                ('image', models.ImageField(upload_to='slider-blog-image/', verbose_name='Imagen')),
                ('content', tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Descripccion de la pagina')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_config_blog', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Blog configuracion',
                'verbose_name_plural': 'blogs Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='blog-images/', verbose_name='Imagen')),
                ('video', models.TextField(blank=True, null=True, verbose_name='Video')),
                ('highlighting_weight', models.PositiveIntegerField(default=100, verbose_name='Peso relativo de destaque')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_category', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('color', models.PositiveIntegerField(blank=True, null=True, verbose_name='Color')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_tag', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Etiqueta de articulo',
                'verbose_name_plural': 'Etiquetas de los articulos',
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='blog-images/', verbose_name='Imagen')),
                ('video', models.TextField(blank=True, null=True, verbose_name='Video')),
                ('highlighting_weight', models.PositiveIntegerField(default=100, verbose_name='Peso relativo de destaque')),
                ('content', tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Políticas de protección de datos')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_article', to='blog.CategoryArticle', verbose_name='Categoria')),
                ('tags', models.ManyToManyField(blank=True, to='blog.BlogTag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_articles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
