# Generated by Django 3.0.6 on 2021-04-18 03:32

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
