# Generated by Django 3.0.6 on 2021-04-18 04:08

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210417_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='first_p',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Primer parrafo'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='intro',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Introduccion'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='second_p',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Segundo parrafo'),
        ),
    ]
