# Generated by Django 3.0.6 on 2021-04-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210417_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='image_secondary',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='second_p',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='image_intro',
            field=models.ImageField(blank=True, null=True, upload_to='blog-images/intro/', verbose_name='Imagen de Introduccion'),
        ),
    ]
