# Generated by Django 3.0.6 on 2021-04-18 04:40

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210417_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='quotes',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Quotes'),
        ),
    ]
